version: '3.8'

services:
  movify-db:
    image: postgres:15
    container_name: movify-db
    restart: always
    environment:
      - POSTGRES_DB=movify-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/movify
    networks:
      - app

  content-service:
    image: content-service:latest
    build:
      context: ./ContentService
      dockerfile: Dockerfile
    depends_on:
      - movify-db
    ports:
      - "8085:8085"
      - "9095:9095"
    environment:
      - GRPC_AUTH_HOST=auth-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movify-db/movify-db
    container_name: content-service
    networks:
      - app

  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8079:8079"
    networks:
      - app

  media-service:
    container_name: media-service
    build:
      context: ./MediaService
      dockerfile: Dockerfile
    ports:
      - "8078:8078"
    networks:
      - app

volumes:
  db:
    driver: local

networks:
  app:
    driver: bridge

