version: '3.8'

services:
  movify-db:
    image: postgres:15
    container_name: movify-db
    restart: always
    environment:
      - POSTGRES_DB=movify-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/movify
    networks:
      - app

  movify-s3:
    image: minio/minio:latest
    container_name: movify-s3
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin_password"
    volumes:
      - s3_data:/data
      - s3_config:/root/.minio
    command: server /data --console-address ":9090"
    networks:
      - app

  content-service:
    image: content-service:latest
    build:
      context: ./ContentService
      dockerfile: Dockerfile
    depends_on:
      - movify-db
    ports:
      - "8085:8085"
      - "9095:9095"
    environment:
      - GRPC_AUTH_HOST=auth-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movify-db/movify-db
    container_name: content-service
    networks:
      - app

  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "8079:8079"
    networks:
      - app

  media-service:
    container_name: media-service
    build:
      context: ./MediaService
      dockerfile: Dockerfile
    depends_on:
      - movify-s3
    ports:
      - "8078:8078"
      - "8077:8077"
    networks:
      - app

  chunker-service:
    container_name: chunker-service
    build:
      context: ./ChunkerService
      dockerfile: Dockerfile
    depends_on:
      - movify-s3
    ports:
      - "8076:8076"
    networks:
      - app

  api-gateway:
    container_name: api-gateway
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    depends_on:
      - content-service
      - media-service
    ports:
      - 8090:8090
    networks:
      - app

  client:
    container_name: client
    build:
      context: ./UI
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
    ports:
      - 5173:5173
    networks:
      - app
    

volumes:
  db:
    driver: local
  s3_data:
    driver: local
  s3_config:
    driver: local

networks:
  app:
    driver: bridge

