# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'content.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontent.proto\x12\x0b\x63om.content\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0fUserRoleRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\" \n\x10UserRoleResponse\x12\x0c\n\x04role\x18\x01 \x01(\t\";\n\x19SetContentImageUrlRequest\x12\x11\n\tcontentId\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"K\n\x19SetEpisodeVideoUrlRequest\x12\x11\n\tepisodeId\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\x88\x02\n\x0e\x43ontentService\x12J\n\x0bGetUserRole\x12\x1c.com.content.UserRoleRequest\x1a\x1d.com.content.UserRoleResponse\x12T\n\x12SetContentImageUrl\x12&.com.content.SetContentImageUrlRequest\x1a\x16.google.protobuf.Empty\x12T\n\x12SetEpisodeVideoUrl\x12&.com.content.SetEpisodeVideoUrlRequest\x1a\x16.google.protobuf.EmptyB\x0bP\x01\xaa\x02\x06Movifyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\252\002\006Movify'
  _globals['_USERROLEREQUEST']._serialized_start=59
  _globals['_USERROLEREQUEST']._serialized_end=91
  _globals['_USERROLERESPONSE']._serialized_start=93
  _globals['_USERROLERESPONSE']._serialized_end=125
  _globals['_SETCONTENTIMAGEURLREQUEST']._serialized_start=127
  _globals['_SETCONTENTIMAGEURLREQUEST']._serialized_end=186
  _globals['_SETEPISODEVIDEOURLREQUEST']._serialized_start=188
  _globals['_SETEPISODEVIDEOURLREQUEST']._serialized_end=263
  _globals['_CONTENTSERVICE']._serialized_start=266
  _globals['_CONTENTSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
