# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x08\x63om.auth\"\'\n\x16ValidationTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"6\n\x17ValidationTokenResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"D\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"Q\n\x14RegisterUserResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x14\n\x0cpasswordHash\x18\x02 \x01(\t\x12\x14\n\x0cpasswordSalt\x18\x03 \x01(\t\"m\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x14\n\x0cpasswordHash\x18\x04 \x01(\t\x12\x14\n\x0cpasswordSalt\x18\x05 \x01(\t\"\"\n\x11LoginUserResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xf8\x01\n\x0b\x41uthService\x12T\n\rValidateToken\x12 .com.auth.ValidationTokenRequest\x1a!.com.auth.ValidationTokenResponse\x12M\n\x0cRegisterUser\x12\x1d.com.auth.RegisterUserRequest\x1a\x1e.com.auth.RegisterUserResponse\x12\x44\n\tLoginUser\x12\x1a.com.auth.LoginUserRequest\x1a\x1b.com.auth.LoginUserResponseB\x0bP\x01\xaa\x02\x06Movifyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\252\002\006Movify'
  _globals['_VALIDATIONTOKENREQUEST']._serialized_start=24
  _globals['_VALIDATIONTOKENREQUEST']._serialized_end=63
  _globals['_VALIDATIONTOKENRESPONSE']._serialized_start=65
  _globals['_VALIDATIONTOKENRESPONSE']._serialized_end=119
  _globals['_REGISTERUSERREQUEST']._serialized_start=121
  _globals['_REGISTERUSERREQUEST']._serialized_end=189
  _globals['_REGISTERUSERRESPONSE']._serialized_start=191
  _globals['_REGISTERUSERRESPONSE']._serialized_end=272
  _globals['_LOGINUSERREQUEST']._serialized_start=274
  _globals['_LOGINUSERREQUEST']._serialized_end=383
  _globals['_LOGINUSERRESPONSE']._serialized_start=385
  _globals['_LOGINUSERRESPONSE']._serialized_end=419
  _globals['_AUTHSERVICE']._serialized_start=422
  _globals['_AUTHSERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
