server:
  port: 8085

spring:
  application:
    name: ContentService

  mvc:
    static-path-pattern: /swagger*

  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_DATABASE:movify-db}"
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs
