server:
  port: 8085

grpc:
  port: 9095
  enable-reflection: true

spring:
  application:
    name: ContentService

  mvc:
    static-path-pattern: /swagger*

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/movify-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

content:
  client:
    auth:
      grpc:
        host: ${GRPC_AUTH_HOST:localhost}
        port: 8079

auth:
  ban-time-in-seconds: 30
  default-attempts-amount: 3
