version: '3.8'

services:
  movify-db:
    image: postgres:15
    container_name: movify-db
    restart: always
    environment:
      - POSTGRES_DB=movify-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/movify

volumes:
  db:
    driver: local
