name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all Docker images
        working-directory: IntegrationTests/Tests
        run: |
          docker compose -f docker-compose.integration.yml build
