name: Pytest Integration Tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"

      - name: Install Dependencies
        working-directory: IntegrationTests/Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run Pytest Integration Tests
        working-directory: IntegrationTests/Tests
        run: |
          pytest -s -v
